services:
  mysql:
    image: mysql:8.0
    container_name: attbancojava
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: bancoaulajava
      MYSQL_USER: usuario
      MYSQL_PASSWORD: senha123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - minha_rede
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  app:
    build:
      context: ./atividadebancodedados
      dockerfile: Dockerfile
    container_name: atividadebancodedados
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/bancoaulajava
      SPRING_DATASOURCE_USERNAME: usuario
      SPRING_DATASOURCE_PASSWORD: senha123
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - minha_rede

volumes:
  mysql_data:
    driver: local

networks:
  minha_rede:
    driver: bridge
